<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>autocomplete_location_trigger</name>
   <tag></tag>
   <elementGuidId>da9318e7-0054-4880-8197-b6508abf8ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li/div/span[contains(text(),&quot;Beatric&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//DIV[@class='select2-result-label'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li/div/span[contains(text(),&quot;Beatric&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
