<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_all_add</name>
   <tag></tag>
   <elementGuidId>dc4db054-b6bf-475d-af19-759269f4277a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[contains(@class,'panel-heading')]//self::*[(text()='Add')]//following-sibling::*//li[${value}]//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[contains(@class,'panel-heading')]//self::*[(text()='Add')]//following-sibling::*//li[${value}]//div</value>
   </webElementProperties>
</WebElementEntity>
